# Generated by Django 2.1.7 on 2019-03-26 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auctions', '0018_auto_20190326_1009'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated at')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_reported', to='auctions.Ad', verbose_name='ad')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads_reported', to=settings.AUTH_USER_MODEL, verbose_name='reporter')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated at')),
                ('reported', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='self_reported', to=settings.AUTH_USER_MODEL, verbose_name='reported')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reported', to=settings.AUTH_USER_MODEL, verbose_name='reporter')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
