stages:
  - test
  - deploy


.test-job: &test-job
    stage: test
    script:
        - apt-get update -qy
        - apt-get install -y python3-dev python3-pip python3-virtualenv sqlite3 libsqlite3-dev
        - cd backend
        - pip3 install virtualenv
        - virtualenv -p python3 testenv
        - source testenv/bin/activate
        - pip3 install -r requirements_test.txt
        - python3 manage.py makemigrations
        - python3 manage.py migrate
        - sqlite3 --version
        - python3 manage.py test


test-django-job:
    stage: test
    image: python:3.7
    only:
        - master
        - gitlab-ci-test
    <<: *test-job


deploy-job:
    stage: deploy
    script:
        - echo "deploy-job alive"
    tags:
        - deploy
    only:
        - master
