stages:
  - test
  - deploy


.test-job: &test-job
    stage: test
    script:
        - apt-get update -qy
        - apt-get install -y python3-dev python3-pip
        - cd backend
        - pip3 install -r requirements.txt
        - python3 manage.py makemigrations --settings=budbua.settings_tests
        - python3 manage.py migrate --settings=budbua.settings_tests
        - python3 manage.py test --settings=budbua.settings_tests


test-django-job:
    stage: test
    image: python:3.7
    only:
        - master
        - gitlab-ci-test
    <<: *test-job


deploy-job:
    stage: deploy
    script:
        - echo "deploy-job alive"
    tags:
        - deploy
    only:
        - master
