stages:
  - test
  - deploy


.test-job: &test-job
    stage: test
    script:
        - apt-get update -qy
        - apt-get install -y python-dev python-pip3
        - cd backend
        - pip3 install -r requirements.txt
        - python manage.py test


test-django-job:
    stage: test
    image: python:3.7
    only:
        - master
        - gitlab-ci-test
    <<: *test-job


deploy-job:
    stage: deploy
    script:
        - echo "deploy-job alive"
    tags:
        - deploy
    only:
        - master
