stages:
  - test
  - deploy


.test-job: &test-job
    stage: test
    services:
        - postgres:latest

    variables:
      POSTGRES_DB: budbuaheaven
      POSTGRES_USER: runner
      POSTGRES_PASSWORD: ""

    script:
        - export DATABASE_URL=postgres://postgres:@postgres:5432/budbuaTest
        - apt-get update -qy
        - apt-get install -y python3-dev python3-pip python3-virtualenv sqlite3 libsqlite3-dev
        - cd backend
        - pip3 install virtualenv
        - virtualenv -p python3 testenv
        - source testenv/bin/activate
        - pip3 install -r requirements_test.txt
        - yes | python3 manage.py makemigrations --settings=budbua.settings_tests --merge
        - python3 manage.py --settings=budbua.settings_tests migrate
        - python3 manage.py test --settings=budbua.settings_tests --verbosity=2

test-django-job:
    stage: test
    image: python:3.7
    only:
        - master
        - gitlab-ci-test
    <<: *test-job


deploy-job:
    stage: deploy

    script:
        - echo "deploy-job alive"
    tags:
        - deploy
    only:
        - master
