stages:
  - test
  - deploy


.test-job: &test-job
    stage: test

    script:
        - apt-get update -qy
        - apt-get install -y python3-dev python3-pip python3-virtualenv sqlite3 libsqlite3-dev
        - cd backend
        - pip3 install -r requirements_test.txt
        - export DJANGO_SETTINGS_MODULE=budbua.settings_tests
        - pip3 install pytest
        - pip3 install pytest-cov
        - pip3 install coverage
        - python3 manage.py makemigrations --settings=budbua.settings_tests --merge --no-input
        - python3 manage.py migrate --settings=budbua.settings_tests --no-input
        - python3 manage.py test --settings=budbua.settings_tests --verbosity=2
        - pytest --cov

.heroku-deploy: &heroku-deploy
    stage: deploy
    script:
        - echo "deb http://toolbelt.heroku.com/ubuntu ./" > /etc/apt/sources.list.d/heroku.list
        - wget -O- https://toolbelt.heroku.com/apt/release.key | apt-key add -
        - apt-get update -qy
        - apt-get install -y heroku-toolbelt
        - apt-get install -y ruby-dev
        - gem install dpl
        - cd backend
        - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY
        - heroku run "python manage.py migrate" --exit-code --app=$HEROKU_APP_NAME
    only:
        - master


django-unit-integration-tests-job:
    stage: test
    image: python:3.7
    only:
        - dev
        - master
        - readme
    <<: *test-job


deploy-heroku-job:
    stage: deploy
    image: python:3.7
    only:
        - master
        - gitlab-ci-test
    <<: *heroku-deploy


.netlify-deploy: &netlify-deploy
    stage: deploy
    script:
        - cd frontend
        - yarn
        - yarn run build
        - cp netlify.toml dist
        - yarn add netlify-cli
        - yarn run netlify deploy -s $NETLIFY_SITE_ID -d "dist" -a $NETLIFY_AUTH_TOKEN --prod
    only:
        - master
        - gitlab-ci-test

deploy-netlify-job:
    stage: deploy
    image: node:latest
    only:
        - master
        - gitlab-ci-test
    <<: *netlify-deploy
