stages:
  - build
  - test
  - deploy

build-job:
    stage: build
    script:
        - echo "build-job alive"
    tags:
        - build

test-job:
    stage: test
    script:
        - echo "test-job alive"
    tags:
        - test

deploy-job:
    stage: deploy
    script:
        - echo "deploy-job alive"
    tags:
        - deploy
