stages:
  - test
  - deploy


.test-job: &test-job
    stage: test

    script:
        - apt-get update -qy
        - apt-get install -y python3-dev python3-pip python3-virtualenv sqlite3 libsqlite3-dev
        - cd backend
        - pip3 install virtualenv
        - virtualenv -p python3 testenv
        - source testenv/bin/activate
        - pip3 install -r requirements_test.txt
        - python3 manage.py test --settings=budbua.settings_tests --verbosity=2


.heroku-deploy: &heroku-deploy
    stage: deploy
    script:
        - apt-get update -qy
        - apt-get install -y ruby-dev
        - gem install dpl
        - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY
    tags:
        - deploy
    only:
        - master
        - gitlab-ci-test

django-unit-integration-tests-job:
    stage: test
    image: python:3.7
    only:
        - master
        - gitlab-ci-test
    <<: *test-job


deploy-heroku-job:
    stage: deploy
    image: python:3.7
    tags:
        - deploy
    only:
        - master
        - gitlab-ci-test
    <<: *heroku-deploy
