# Generated by Django 2.1.7 on 2019-02-13 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20190213_1606'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='bid',
            options={'ordering': ('-created_at',)},
        ),
        migrations.RemoveField(
            model_name='ad',
            name='minimum_bid',
        ),
        migrations.AlterField(
            model_name='bid',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auctions.Ad'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='bidder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to=settings.AUTH_USER_MODEL),
        ),
    ]
