# Generated by Django 2.1.7 on 2019-02-13 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20190213_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='minimum_bid',
            field=models.IntegerField(default=0, verbose_name='minimum bid'),
        ),
    ]
