# Generated by Django 2.1.7 on 2019-02-14 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20190214_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='minimum_bid',
        ),
    ]
