# Generated by Django 2.1.7 on 2019-02-14 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20190214_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='zip_code',
            field=models.IntegerField(default=7030, verbose_name='zip code'),
            preserve_default=False,
        ),
    ]
