# Generated by Django 2.1.7 on 2019-02-19 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20190215_1248'),
        ('auctions', '0010_ad_minimum_bid'),
    ]

    operations = [
    ]
