# Generated by Django 2.1.7 on 2019-02-26 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_merge_20190219_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='image_string',
            field=models.TextField(null=True, verbose_name='image string'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='bidder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bids', to=settings.AUTH_USER_MODEL, verbose_name='bidder'),
        ),
    ]
