# Generated by Django 2.1.7 on 2019-02-26 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20190226_1146'),
        ('auctions', '0012_auto_20190219_1012'),
        ('auctions', '0012_auto_20190222_1304'),
    ]

    operations = [
    ]
