# Generated by Django 2.1.7 on 2019-02-26 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20190225_1829'),
        ('auctions', '0012_auto_20190222_1304'),
    ]

    operations = [
    ]
