# Generated by Django 2.1.7 on 2019-02-26 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_merge_20190226_1255'),
        ('auctions', '0012_auto_20190226_1146'),
    ]

    operations = [
    ]
