# Generated by Django 2.1.7 on 2019-02-28 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_merge_20190226_1220'),
        ('auctions', '0014_merge_20190226_1330'),
    ]

    operations = [
    ]
