# Generated by Django 2.1.7 on 2019-02-28 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_merge_20190226_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='image_string',
            field=models.TextField(blank=True, null=True, verbose_name='image string'),
        ),
    ]
