# Generated by Django 2.1.7 on 2019-03-21 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_merge_20190228_0810'),
        ('auctions', '0015_auto_20190228_0911'),
    ]

    operations = [
    ]
