# Generated by Django 2.1.7 on 2019-03-19 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_merge_20190228_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='image_string',
            field=models.TextField(blank=True, null=True, verbose_name='image string'),
        ),
    ]
