# Generated by Django 2.1.7 on 2019-03-26 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_merge_20190321_0743'),
        ('auctions', '0016_auto_20190319_1134'),
    ]

    operations = [
    ]
