# Generated by Django 2.1.7 on 2019-03-26 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_merge_20190326_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='zip_code',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='zip code'),
        ),
    ]
