# Generated by Django 2.1.7 on 2019-03-21 08:01
from django.contrib.auth.models import Group
from django.db import migrations


def create_owner_group(apps, schema_editor):
    Group.objects.create(
        name='Owner',
    )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_owner_group)
    ]
