# Generated by Django 2.1.7 on 2019-02-12 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='lars', max_length=255, unique=True, verbose_name='username'),
            preserve_default=False,
        ),
    ]
